/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    String name="만다린";
    public String getGreeting() {
        return name;
        
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
