<<<<<<< HEAD
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        System.out.println("오");
        System.out.println("호");
        System.out.println("라");
        System.out.println("...");
    }
}
=======
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "충돌충돌충돌충돌";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("집집집집");
        
        System.out.println("갈땐 가더라도 담배한대정도는 괜잖아?");
    }
}
>>>>>>> 05fea1eba2540b02340026874ed56034c4f6ce76
